name: captcha

services:
  service:
    build: .
    container_name: service
    image: captcha-service:latest
    pull_policy: always
    ports:
      - "8500:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    env_file:
      - .env
    command: uvicorn main:app --host ${HOST:-0.0.0.0} --port ${PORT:-8000} --reload
    networks:
      - app-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./static:/var/www/html
  #   depends_on:
  #     - service
  #   networks:
  #     - app-network

volumes:
  app-data:

networks:
  app-network:
    driver: bridge